name: "fuel_lakehouse"
version: "1.0.0"
config-version: 2

profile: "fuel_lakehouse"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  fuel_lakehouse:
    staging:
      +materialized: view
      +schema: silver
    marts:
      +materialized: table
      +schema: gold
